### ISSUE TITLE
[ONBOARD] @JC-Tartu tasks to get started before the first class

### ISSUE THREAD

**Issue by altosaar** [onefact/datathinking.org#7]
- [ ] Read datathinking.org/university-of-tartu/getting-started
- [ ] Install a package manager (Chocolatey for Windows or Homebrew for Mac)
- [ ] Install Visual Studio Code
- [ ] Activate GitHub Student Developer Pack: https://education.github.com/pack
- [ ] Install the Copilot extension for Visual Studio Code: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot 
- [ ] Sign into Visual Studio Code to activate the GitHub Student Developer Pack
- [ ] Sign up for datathinking.zulipchat.com
- [ ] Post a message in the General stream topic called "intros"
- [ ] Comment on this issue or ask on the Zulip chat if you run into any trouble, have any doubts or questions. Please include which task you were trying to complete, what you tried (including asking ChatGPT https://chat.openai.com/chat for help and the prompt you used, and what part of it is not working - include screenshots, screen recordings if needed)

**Comment by JC-Tartu** [comment]
a) Can I mark tasks done in the list above? How?
b) Can't I activate GitHub Student Developer Pack on GitHub with my personal email
c) Can't activate GitHub Student Developer Pack inside VSC w/out activation in GitHub
d) To install Chocolatey on Windows you need to open powershell as admin
